name: CI/CD
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'

  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'

env:
  # https://typicode.github.io/husky/#/?id=with-env-variables
  HUSKY: '0'

jobs:
  build:
    name: 'Build Project'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Build project
        run: yarn build
